/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GoogleGenAI } from "@google/genai";

export async function generateImage(prompt: string, options: { 
  model?: string;
  imageSize?: "512px" | "1K" | "2K" | "4K";
  aspectRatio?: "1:1" | "3:4" | "4:3" | "9:16" | "16:9" | "1:4" | "1:8" | "4:1" | "8:1";
  imageBytes?: string;
  mimeType?: string;
} = {}) {
  const { 
    model = "gemini-3.1-flash-image-preview",
    imageSize = "1K",
    aspectRatio = "1:1",
    imageBytes,
    mimeType
  } = options;

  // Crucial: Create a new instance right before the call to ensure the latest API key is used
  // as per the gemini-api skill instructions for paid models.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || "" });

  const contents: any[] = [{ text: prompt }];
  
  if (imageBytes && mimeType) {
    contents.unshift({
      inlineData: {
        data: imageBytes,
        mimeType: mimeType
      }
    });
  }

  try {
    const response = await ai.models.generateContent({
      model,
      contents: { parts: contents },
      config: {
        imageConfig: {
          aspectRatio,
          imageSize
        }
      }
    });

    const candidate = response.candidates?.[0];
    if (!candidate || !candidate.content || !candidate.content.parts) {
      throw new Error("No image generated by the backend.");
    }

    for (const part of candidate.content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }

    throw new Error("The model did not return an image part.");
  } catch (error: any) {
    if (error?.message?.includes("Requested entity was not found.")) {
      throw new Error("KEY_RESET_REQUIRED");
    }
    throw error;
  }
}

export async function askOrthodoxAI(
  message: string, 
  chatHistory: { role: 'user' | 'model', text: string }[], 
  lang: string
): Promise<string> {
  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || process.env.API_KEY || "" });
  const model = "gemini-3.5-flash";

  const systemInstruction = `You are a highly knowledgeable, respectful, and compassionate Ethiopian and Eritrean Orthodox Tewahedo Church theologian, scholar, and spiritual assistant. 
Your goal is to help users learn about the history, dogmas, liturgies (Kidase), spiritual songs (Mezmur & Zema), sacraments, fasting seasons (Tsom), monthly & annual holidays, saints, angels, and general biblical teachings of the Orthodox Tewahedo Church.
Always maintain a humble, spiritually comforting, respectful, and canonical Orthodox tone. 
Where spiritually relevant, you may include traditional blessings or references (e.g., in Amharic: 'በስመ አብ ወወልድ ወመንፈስ ቅዱስ አሐዱ አምላክ አሜን' or 'እግዚአብሔር ይመስገን').
Ensure you answer in the requested language corresponding to the language parameter: '${lang}' (which will be 'am' for Amharic, 'ti' for Tigrinya, 'or' for Oromo, or 'en' for English). 
Stay strictly faithful to the teachings of the Orthodox Tewahedo Church and do not introduce modern secular or non-Orthodox dogmatic reinterpretations.`;

  const contents = chatHistory.map(h => ({
    role: h.role,
    parts: [{ text: h.text }]
  }));

  contents.push({
    role: 'user',
    parts: [{ text: message }]
  });

  try {
    const response = await ai.models.generateContent({
      model,
      contents,
      config: {
        systemInstruction,
        temperature: 0.7,
      }
    });

    if (!response.text) {
      throw new Error("No response from AI.");
    }

    return response.text;
  } catch (error: any) {
    console.error("Gemini API Error in askOrthodoxAI:", error);
    if (error?.message?.includes("Requested entity was not found.")) {
      throw new Error("KEY_RESET_REQUIRED");
    }
    throw error;
  }
}

