import 'package:hive/hive.dart';

part 'song.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class Song extends HiveObject {
  @HiveField(0)
  final String id;
  @HiveField(1)
  final String title;
  @HiveField(2)
  final String artist;
  @HiveField(3)
  final String category;
  @HiveField(4)
  final String duration;
  @HiveField(5)
  final String filePath;
  @HiveField(6)
  bool isFavorite;
  @HiveField(7)
  bool isFeatured;
  @HiveField(8)
  final DateTime addedAt;

  Song({
    required this.id,
    required this.title,
    required this.artist,
    required this.category,
    required this.duration,
    required this.filePath,
    this.isFavorite = false,
    this.isFeatured = false,
    required this.addedAt,
  });
}
